package com.grooveguang.bean;

import java.util.Date;

public class MallCommentImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_comment_image.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_comment_image.pl_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer plId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_comment_image.url
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_comment_image.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Date chjshj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_comment_image.Id
     *
     * @return the value of t_mall_comment_image.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_comment_image.Id
     *
     * @param id the value for t_mall_comment_image.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_comment_image.pl_id
     *
     * @return the value of t_mall_comment_image.pl_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getPlId() {
        return plId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_comment_image.pl_id
     *
     * @param plId the value for t_mall_comment_image.pl_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setPlId(Integer plId) {
        this.plId = plId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_comment_image.url
     *
     * @return the value of t_mall_comment_image.url
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_comment_image.url
     *
     * @param url the value for t_mall_comment_image.url
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_comment_image.chjshj
     *
     * @return the value of t_mall_comment_image.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Date getChjshj() {
        return chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_comment_image.chjshj
     *
     * @param chjshj the value for t_mall_comment_image.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setChjshj(Date chjshj) {
        this.chjshj = chjshj;
    }
}