package com.grooveguang.bean;

public class MallClass1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_class_1.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_class_1.flmch1
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String flmch1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_class_1.Id
     *
     * @return the value of t_mall_class_1.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_class_1.Id
     *
     * @param id the value for t_mall_class_1.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_class_1.flmch1
     *
     * @return the value of t_mall_class_1.flmch1
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getFlmch1() {
        return flmch1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_class_1.flmch1
     *
     * @param flmch1 the value for t_mall_class_1.flmch1
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setFlmch1(String flmch1) {
        this.flmch1 = flmch1 == null ? null : flmch1.trim();
    }
}