package com.grooveguang.bean;

import java.util.Date;

public class MallSkuAttrValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku_attr_value.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku_attr_value.shxm_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer shxmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku_attr_value.shxzh_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer shxzhId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku_attr_value.shp_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer shpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku_attr_value.is_sku
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String isSku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku_attr_value.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Date chjshj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku_attr_value.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer skuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku_attr_value.Id
     *
     * @return the value of t_mall_sku_attr_value.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku_attr_value.Id
     *
     * @param id the value for t_mall_sku_attr_value.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku_attr_value.shxm_id
     *
     * @return the value of t_mall_sku_attr_value.shxm_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getShxmId() {
        return shxmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku_attr_value.shxm_id
     *
     * @param shxmId the value for t_mall_sku_attr_value.shxm_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShxmId(Integer shxmId) {
        this.shxmId = shxmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku_attr_value.shxzh_id
     *
     * @return the value of t_mall_sku_attr_value.shxzh_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getShxzhId() {
        return shxzhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku_attr_value.shxzh_id
     *
     * @param shxzhId the value for t_mall_sku_attr_value.shxzh_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShxzhId(Integer shxzhId) {
        this.shxzhId = shxzhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku_attr_value.shp_id
     *
     * @return the value of t_mall_sku_attr_value.shp_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getShpId() {
        return shpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku_attr_value.shp_id
     *
     * @param shpId the value for t_mall_sku_attr_value.shp_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShpId(Integer shpId) {
        this.shpId = shpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku_attr_value.is_sku
     *
     * @return the value of t_mall_sku_attr_value.is_sku
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getIsSku() {
        return isSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku_attr_value.is_sku
     *
     * @param isSku the value for t_mall_sku_attr_value.is_sku
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setIsSku(String isSku) {
        this.isSku = isSku == null ? null : isSku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku_attr_value.chjshj
     *
     * @return the value of t_mall_sku_attr_value.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Date getChjshj() {
        return chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku_attr_value.chjshj
     *
     * @param chjshj the value for t_mall_sku_attr_value.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setChjshj(Date chjshj) {
        this.chjshj = chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku_attr_value.sku_id
     *
     * @return the value of t_mall_sku_attr_value.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku_attr_value.sku_id
     *
     * @param skuId the value for t_mall_sku_attr_value.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }
}