package com.grooveguang.bean;

import java.math.BigDecimal;
import java.util.Date;

public class MallOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order.shhr
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String shhr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order.zje
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private BigDecimal zje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order.jdh
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer jdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order.yh_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer yhId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Date chjshj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order.yjsdshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Date yjsdshj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order.dzh_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer dzhId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order.dzh_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String dzhMch;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order.Id
     *
     * @return the value of t_mall_order.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order.Id
     *
     * @param id the value for t_mall_order.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order.shhr
     *
     * @return the value of t_mall_order.shhr
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getShhr() {
        return shhr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order.shhr
     *
     * @param shhr the value for t_mall_order.shhr
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShhr(String shhr) {
        this.shhr = shhr == null ? null : shhr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order.zje
     *
     * @return the value of t_mall_order.zje
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public BigDecimal getZje() {
        return zje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order.zje
     *
     * @param zje the value for t_mall_order.zje
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setZje(BigDecimal zje) {
        this.zje = zje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order.jdh
     *
     * @return the value of t_mall_order.jdh
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getJdh() {
        return jdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order.jdh
     *
     * @param jdh the value for t_mall_order.jdh
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setJdh(Integer jdh) {
        this.jdh = jdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order.yh_id
     *
     * @return the value of t_mall_order.yh_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getYhId() {
        return yhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order.yh_id
     *
     * @param yhId the value for t_mall_order.yh_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setYhId(Integer yhId) {
        this.yhId = yhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order.chjshj
     *
     * @return the value of t_mall_order.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Date getChjshj() {
        return chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order.chjshj
     *
     * @param chjshj the value for t_mall_order.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setChjshj(Date chjshj) {
        this.chjshj = chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order.yjsdshj
     *
     * @return the value of t_mall_order.yjsdshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Date getYjsdshj() {
        return yjsdshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order.yjsdshj
     *
     * @param yjsdshj the value for t_mall_order.yjsdshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setYjsdshj(Date yjsdshj) {
        this.yjsdshj = yjsdshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order.dzh_id
     *
     * @return the value of t_mall_order.dzh_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getDzhId() {
        return dzhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order.dzh_id
     *
     * @param dzhId the value for t_mall_order.dzh_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setDzhId(Integer dzhId) {
        this.dzhId = dzhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order.dzh_mch
     *
     * @return the value of t_mall_order.dzh_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getDzhMch() {
        return dzhMch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order.dzh_mch
     *
     * @param dzhMch the value for t_mall_order.dzh_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setDzhMch(String dzhMch) {
        this.dzhMch = dzhMch == null ? null : dzhMch.trim();
    }
}