package com.grooveguang.bean;

import java.math.BigDecimal;
import java.util.Date;

public class MallSku {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku.shp_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer shpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku.kc
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer kc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku.jg
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private BigDecimal jg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Date chjshj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku.sku_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String skuMch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku.sku_xl
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer skuXl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku.kcdz
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String kcdz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku.Id
     *
     * @return the value of t_mall_sku.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku.Id
     *
     * @param id the value for t_mall_sku.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku.shp_id
     *
     * @return the value of t_mall_sku.shp_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getShpId() {
        return shpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku.shp_id
     *
     * @param shpId the value for t_mall_sku.shp_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShpId(Integer shpId) {
        this.shpId = shpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku.kc
     *
     * @return the value of t_mall_sku.kc
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getKc() {
        return kc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku.kc
     *
     * @param kc the value for t_mall_sku.kc
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setKc(Integer kc) {
        this.kc = kc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku.jg
     *
     * @return the value of t_mall_sku.jg
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public BigDecimal getJg() {
        return jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku.jg
     *
     * @param jg the value for t_mall_sku.jg
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setJg(BigDecimal jg) {
        this.jg = jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku.chjshj
     *
     * @return the value of t_mall_sku.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Date getChjshj() {
        return chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku.chjshj
     *
     * @param chjshj the value for t_mall_sku.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setChjshj(Date chjshj) {
        this.chjshj = chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku.sku_mch
     *
     * @return the value of t_mall_sku.sku_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getSkuMch() {
        return skuMch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku.sku_mch
     *
     * @param skuMch the value for t_mall_sku.sku_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuMch(String skuMch) {
        this.skuMch = skuMch == null ? null : skuMch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku.sku_xl
     *
     * @return the value of t_mall_sku.sku_xl
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getSkuXl() {
        return skuXl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku.sku_xl
     *
     * @param skuXl the value for t_mall_sku.sku_xl
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuXl(Integer skuXl) {
        this.skuXl = skuXl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku.kcdz
     *
     * @return the value of t_mall_sku.kcdz
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getKcdz() {
        return kcdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku.kcdz
     *
     * @param kcdz the value for t_mall_sku.kcdz
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setKcdz(String kcdz) {
        this.kcdz = kcdz == null ? null : kcdz.trim();
    }
}