package com.grooveguang.bean;

import java.util.Date;

public class MallValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_value.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_value.shxzh
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String shxzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_value.shfqy
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String shfqy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_value.shxm_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer shxmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_value.shxzh_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String shxzhMch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_value.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Date chjshj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_value.Id
     *
     * @return the value of t_mall_value.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_value.Id
     *
     * @param id the value for t_mall_value.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_value.shxzh
     *
     * @return the value of t_mall_value.shxzh
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getShxzh() {
        return shxzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_value.shxzh
     *
     * @param shxzh the value for t_mall_value.shxzh
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShxzh(String shxzh) {
        this.shxzh = shxzh == null ? null : shxzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_value.shfqy
     *
     * @return the value of t_mall_value.shfqy
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getShfqy() {
        return shfqy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_value.shfqy
     *
     * @param shfqy the value for t_mall_value.shfqy
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShfqy(String shfqy) {
        this.shfqy = shfqy == null ? null : shfqy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_value.shxm_id
     *
     * @return the value of t_mall_value.shxm_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getShxmId() {
        return shxmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_value.shxm_id
     *
     * @param shxmId the value for t_mall_value.shxm_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShxmId(Integer shxmId) {
        this.shxmId = shxmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_value.shxzh_mch
     *
     * @return the value of t_mall_value.shxzh_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getShxzhMch() {
        return shxzhMch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_value.shxzh_mch
     *
     * @param shxzhMch the value for t_mall_value.shxzh_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShxzhMch(String shxzhMch) {
        this.shxzhMch = shxzhMch == null ? null : shxzhMch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_value.chjshj
     *
     * @return the value of t_mall_value.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Date getChjshj() {
        return chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_value.chjshj
     *
     * @param chjshj the value for t_mall_value.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setChjshj(Date chjshj) {
        this.chjshj = chjshj;
    }
}