package com.grooveguang.bean;

import java.math.BigDecimal;

public class MallShoppingCarInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.sku_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String skuMch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.sku_jg
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private BigDecimal skuJg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.yh_xm
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String yhXm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.yh_nch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String yhNch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.yh_dz
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String yhDz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.shp_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String shpMch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.shp_tp
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String shpTp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.sku_kc
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer skuKc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar_info.sku_shx
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String skuShx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.Id
     *
     * @return the value of t_mall_shoppingcar_info.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.Id
     *
     * @param id the value for t_mall_shoppingcar_info.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.sku_mch
     *
     * @return the value of t_mall_shoppingcar_info.sku_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getSkuMch() {
        return skuMch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.sku_mch
     *
     * @param skuMch the value for t_mall_shoppingcar_info.sku_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuMch(String skuMch) {
        this.skuMch = skuMch == null ? null : skuMch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.sku_jg
     *
     * @return the value of t_mall_shoppingcar_info.sku_jg
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public BigDecimal getSkuJg() {
        return skuJg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.sku_jg
     *
     * @param skuJg the value for t_mall_shoppingcar_info.sku_jg
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuJg(BigDecimal skuJg) {
        this.skuJg = skuJg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.yh_xm
     *
     * @return the value of t_mall_shoppingcar_info.yh_xm
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getYhXm() {
        return yhXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.yh_xm
     *
     * @param yhXm the value for t_mall_shoppingcar_info.yh_xm
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setYhXm(String yhXm) {
        this.yhXm = yhXm == null ? null : yhXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.yh_nch
     *
     * @return the value of t_mall_shoppingcar_info.yh_nch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getYhNch() {
        return yhNch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.yh_nch
     *
     * @param yhNch the value for t_mall_shoppingcar_info.yh_nch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setYhNch(String yhNch) {
        this.yhNch = yhNch == null ? null : yhNch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.yh_dz
     *
     * @return the value of t_mall_shoppingcar_info.yh_dz
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getYhDz() {
        return yhDz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.yh_dz
     *
     * @param yhDz the value for t_mall_shoppingcar_info.yh_dz
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setYhDz(String yhDz) {
        this.yhDz = yhDz == null ? null : yhDz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.shp_mch
     *
     * @return the value of t_mall_shoppingcar_info.shp_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getShpMch() {
        return shpMch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.shp_mch
     *
     * @param shpMch the value for t_mall_shoppingcar_info.shp_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShpMch(String shpMch) {
        this.shpMch = shpMch == null ? null : shpMch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.shp_tp
     *
     * @return the value of t_mall_shoppingcar_info.shp_tp
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getShpTp() {
        return shpTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.shp_tp
     *
     * @param shpTp the value for t_mall_shoppingcar_info.shp_tp
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShpTp(String shpTp) {
        this.shpTp = shpTp == null ? null : shpTp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.sku_kc
     *
     * @return the value of t_mall_shoppingcar_info.sku_kc
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getSkuKc() {
        return skuKc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.sku_kc
     *
     * @param skuKc the value for t_mall_shoppingcar_info.sku_kc
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuKc(Integer skuKc) {
        this.skuKc = skuKc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar_info.sku_shx
     *
     * @return the value of t_mall_shoppingcar_info.sku_shx
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getSkuShx() {
        return skuShx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar_info.sku_shx
     *
     * @param skuShx the value for t_mall_shoppingcar_info.sku_shx
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuShx(String skuShx) {
        this.skuShx = skuShx == null ? null : skuShx.trim();
    }
}