package com.grooveguang.bean;

public class MallSkuImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku_image.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku_image.url
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku_image.zy
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String zy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_sku_image.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer skuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku_image.Id
     *
     * @return the value of t_mall_sku_image.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku_image.Id
     *
     * @param id the value for t_mall_sku_image.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku_image.url
     *
     * @return the value of t_mall_sku_image.url
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku_image.url
     *
     * @param url the value for t_mall_sku_image.url
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku_image.zy
     *
     * @return the value of t_mall_sku_image.zy
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getZy() {
        return zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku_image.zy
     *
     * @param zy the value for t_mall_sku_image.zy
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setZy(String zy) {
        this.zy = zy == null ? null : zy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_sku_image.sku_id
     *
     * @return the value of t_mall_sku_image.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_sku_image.sku_id
     *
     * @param skuId the value for t_mall_sku_image.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }
}