package com.grooveguang.bean;

import java.util.Date;

public class MallProductComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_comment.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_comment.yh_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer yhId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_comment.plnr
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String plnr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_comment.plshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Date plshj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_comment.hpjb
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer hpjb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_comment.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_comment.sku_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String skuMch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_comment.shp_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer shpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_comment.shp_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String shpMch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_comment.dd_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer ddId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_comment.Id
     *
     * @return the value of t_mall_product_comment.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_comment.Id
     *
     * @param id the value for t_mall_product_comment.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_comment.yh_id
     *
     * @return the value of t_mall_product_comment.yh_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getYhId() {
        return yhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_comment.yh_id
     *
     * @param yhId the value for t_mall_product_comment.yh_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setYhId(Integer yhId) {
        this.yhId = yhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_comment.plnr
     *
     * @return the value of t_mall_product_comment.plnr
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getPlnr() {
        return plnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_comment.plnr
     *
     * @param plnr the value for t_mall_product_comment.plnr
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setPlnr(String plnr) {
        this.plnr = plnr == null ? null : plnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_comment.plshj
     *
     * @return the value of t_mall_product_comment.plshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Date getPlshj() {
        return plshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_comment.plshj
     *
     * @param plshj the value for t_mall_product_comment.plshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setPlshj(Date plshj) {
        this.plshj = plshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_comment.hpjb
     *
     * @return the value of t_mall_product_comment.hpjb
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getHpjb() {
        return hpjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_comment.hpjb
     *
     * @param hpjb the value for t_mall_product_comment.hpjb
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setHpjb(Integer hpjb) {
        this.hpjb = hpjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_comment.sku_id
     *
     * @return the value of t_mall_product_comment.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_comment.sku_id
     *
     * @param skuId the value for t_mall_product_comment.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_comment.sku_mch
     *
     * @return the value of t_mall_product_comment.sku_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getSkuMch() {
        return skuMch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_comment.sku_mch
     *
     * @param skuMch the value for t_mall_product_comment.sku_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuMch(String skuMch) {
        this.skuMch = skuMch == null ? null : skuMch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_comment.shp_id
     *
     * @return the value of t_mall_product_comment.shp_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getShpId() {
        return shpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_comment.shp_id
     *
     * @param shpId the value for t_mall_product_comment.shp_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShpId(Integer shpId) {
        this.shpId = shpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_comment.shp_mch
     *
     * @return the value of t_mall_product_comment.shp_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getShpMch() {
        return shpMch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_comment.shp_mch
     *
     * @param shpMch the value for t_mall_product_comment.shp_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShpMch(String shpMch) {
        this.shpMch = shpMch == null ? null : shpMch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_comment.dd_id
     *
     * @return the value of t_mall_product_comment.dd_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getDdId() {
        return ddId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_comment.dd_id
     *
     * @param ddId the value for t_mall_product_comment.dd_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setDdId(Integer ddId) {
        this.ddId = ddId;
    }
}