package com.grooveguang.bean;

public class MallFlowInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_flow_info.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_flow_info.Id
     *
     * @return the value of t_mall_flow_info.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_flow_info.Id
     *
     * @param id the value for t_mall_flow_info.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }
}