package com.grooveguang.bean;

import java.util.Date;

public class MallProductSkuInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.shp_ys
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer shpYs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.shp_bb
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer shpBb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.shp_msh
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String shpMsh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.shp_lb
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String shpLb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.pp_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer ppId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.shpz_zhl
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String shpzZhl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.shp_chc
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String shpChc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_product_sku_info.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Date chjshj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.shp_ys
     *
     * @return the value of t_mall_product_sku_info.shp_ys
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getShpYs() {
        return shpYs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.shp_ys
     *
     * @param shpYs the value for t_mall_product_sku_info.shp_ys
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShpYs(Integer shpYs) {
        this.shpYs = shpYs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.shp_bb
     *
     * @return the value of t_mall_product_sku_info.shp_bb
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getShpBb() {
        return shpBb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.shp_bb
     *
     * @param shpBb the value for t_mall_product_sku_info.shp_bb
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShpBb(Integer shpBb) {
        this.shpBb = shpBb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.sku_id
     *
     * @return the value of t_mall_product_sku_info.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.sku_id
     *
     * @param skuId the value for t_mall_product_sku_info.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.shp_msh
     *
     * @return the value of t_mall_product_sku_info.shp_msh
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getShpMsh() {
        return shpMsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.shp_msh
     *
     * @param shpMsh the value for t_mall_product_sku_info.shp_msh
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShpMsh(String shpMsh) {
        this.shpMsh = shpMsh == null ? null : shpMsh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.shp_lb
     *
     * @return the value of t_mall_product_sku_info.shp_lb
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getShpLb() {
        return shpLb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.shp_lb
     *
     * @param shpLb the value for t_mall_product_sku_info.shp_lb
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShpLb(String shpLb) {
        this.shpLb = shpLb == null ? null : shpLb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.pp_id
     *
     * @return the value of t_mall_product_sku_info.pp_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getPpId() {
        return ppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.pp_id
     *
     * @param ppId the value for t_mall_product_sku_info.pp_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setPpId(Integer ppId) {
        this.ppId = ppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.shpz_zhl
     *
     * @return the value of t_mall_product_sku_info.shpz_zhl
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getShpzZhl() {
        return shpzZhl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.shpz_zhl
     *
     * @param shpzZhl the value for t_mall_product_sku_info.shpz_zhl
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShpzZhl(String shpzZhl) {
        this.shpzZhl = shpzZhl == null ? null : shpzZhl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.shp_chc
     *
     * @return the value of t_mall_product_sku_info.shp_chc
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getShpChc() {
        return shpChc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.shp_chc
     *
     * @param shpChc the value for t_mall_product_sku_info.shp_chc
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShpChc(String shpChc) {
        this.shpChc = shpChc == null ? null : shpChc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_product_sku_info.chjshj
     *
     * @return the value of t_mall_product_sku_info.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Date getChjshj() {
        return chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_product_sku_info.chjshj
     *
     * @param chjshj the value for t_mall_product_sku_info.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setChjshj(Date chjshj) {
        this.chjshj = chjshj;
    }
}