package com.grooveguang.bean;

import java.math.BigDecimal;
import java.util.Date;

public class MallShoppingCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.sku_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String skuMch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.sku_jg
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private BigDecimal skuJg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.tjshl
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer tjshl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.hj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private BigDecimal hj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.yh_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer yhId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.shp_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer shpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Date chjshj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.shp_tp
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String shpTp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.shfxz
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String shfxz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_shoppingcar.kcdz
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String kcdz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.Id
     *
     * @return the value of t_mall_shoppingcar.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.Id
     *
     * @param id the value for t_mall_shoppingcar.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.sku_mch
     *
     * @return the value of t_mall_shoppingcar.sku_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getSkuMch() {
        return skuMch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.sku_mch
     *
     * @param skuMch the value for t_mall_shoppingcar.sku_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuMch(String skuMch) {
        this.skuMch = skuMch == null ? null : skuMch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.sku_jg
     *
     * @return the value of t_mall_shoppingcar.sku_jg
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public BigDecimal getSkuJg() {
        return skuJg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.sku_jg
     *
     * @param skuJg the value for t_mall_shoppingcar.sku_jg
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuJg(BigDecimal skuJg) {
        this.skuJg = skuJg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.tjshl
     *
     * @return the value of t_mall_shoppingcar.tjshl
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getTjshl() {
        return tjshl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.tjshl
     *
     * @param tjshl the value for t_mall_shoppingcar.tjshl
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setTjshl(Integer tjshl) {
        this.tjshl = tjshl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.hj
     *
     * @return the value of t_mall_shoppingcar.hj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public BigDecimal getHj() {
        return hj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.hj
     *
     * @param hj the value for t_mall_shoppingcar.hj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setHj(BigDecimal hj) {
        this.hj = hj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.yh_id
     *
     * @return the value of t_mall_shoppingcar.yh_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getYhId() {
        return yhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.yh_id
     *
     * @param yhId the value for t_mall_shoppingcar.yh_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setYhId(Integer yhId) {
        this.yhId = yhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.shp_id
     *
     * @return the value of t_mall_shoppingcar.shp_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getShpId() {
        return shpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.shp_id
     *
     * @param shpId the value for t_mall_shoppingcar.shp_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShpId(Integer shpId) {
        this.shpId = shpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.chjshj
     *
     * @return the value of t_mall_shoppingcar.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Date getChjshj() {
        return chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.chjshj
     *
     * @param chjshj the value for t_mall_shoppingcar.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setChjshj(Date chjshj) {
        this.chjshj = chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.sku_id
     *
     * @return the value of t_mall_shoppingcar.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.sku_id
     *
     * @param skuId the value for t_mall_shoppingcar.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.shp_tp
     *
     * @return the value of t_mall_shoppingcar.shp_tp
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getShpTp() {
        return shpTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.shp_tp
     *
     * @param shpTp the value for t_mall_shoppingcar.shp_tp
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShpTp(String shpTp) {
        this.shpTp = shpTp == null ? null : shpTp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.shfxz
     *
     * @return the value of t_mall_shoppingcar.shfxz
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getShfxz() {
        return shfxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.shfxz
     *
     * @param shfxz the value for t_mall_shoppingcar.shfxz
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShfxz(String shfxz) {
        this.shfxz = shfxz == null ? null : shfxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_shoppingcar.kcdz
     *
     * @return the value of t_mall_shoppingcar.kcdz
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getKcdz() {
        return kcdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_shoppingcar.kcdz
     *
     * @param kcdz the value for t_mall_shoppingcar.kcdz
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setKcdz(String kcdz) {
        this.kcdz = kcdz == null ? null : kcdz.trim();
    }
}