package com.grooveguang.bean;

public class MallOrderPhase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order_phase.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order_phase.jdh
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer jdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order_phase.jdmsh
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String jdmsh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order_phase.Id
     *
     * @return the value of t_mall_order_phase.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order_phase.Id
     *
     * @param id the value for t_mall_order_phase.Id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order_phase.jdh
     *
     * @return the value of t_mall_order_phase.jdh
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getJdh() {
        return jdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order_phase.jdh
     *
     * @param jdh the value for t_mall_order_phase.jdh
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setJdh(Integer jdh) {
        this.jdh = jdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order_phase.jdmsh
     *
     * @return the value of t_mall_order_phase.jdmsh
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getJdmsh() {
        return jdmsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order_phase.jdmsh
     *
     * @param jdmsh the value for t_mall_order_phase.jdmsh
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setJdmsh(String jdmsh) {
        this.jdmsh = jdmsh == null ? null : jdmsh.trim();
    }
}