package com.grooveguang.bean;

import java.math.BigDecimal;
import java.util.Date;

public class MallOrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order_info.id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order_info.dd_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer ddId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order_info.flow_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer flowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order_info.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order_info.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Date chjshj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order_info.sku_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String skuMch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order_info.shp_tp
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String shpTp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order_info.sku_jg
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private BigDecimal skuJg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order_info.sku_shl
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer skuShl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order_info.sku_kcdz
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private String skuKcdz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mall_order_info.gwch_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    private Integer gwchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order_info.id
     *
     * @return the value of t_mall_order_info.id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order_info.id
     *
     * @param id the value for t_mall_order_info.id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order_info.dd_id
     *
     * @return the value of t_mall_order_info.dd_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getDdId() {
        return ddId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order_info.dd_id
     *
     * @param ddId the value for t_mall_order_info.dd_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setDdId(Integer ddId) {
        this.ddId = ddId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order_info.flow_id
     *
     * @return the value of t_mall_order_info.flow_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order_info.flow_id
     *
     * @param flowId the value for t_mall_order_info.flow_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setFlowId(Integer flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order_info.sku_id
     *
     * @return the value of t_mall_order_info.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order_info.sku_id
     *
     * @param skuId the value for t_mall_order_info.sku_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order_info.chjshj
     *
     * @return the value of t_mall_order_info.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Date getChjshj() {
        return chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order_info.chjshj
     *
     * @param chjshj the value for t_mall_order_info.chjshj
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setChjshj(Date chjshj) {
        this.chjshj = chjshj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order_info.sku_mch
     *
     * @return the value of t_mall_order_info.sku_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getSkuMch() {
        return skuMch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order_info.sku_mch
     *
     * @param skuMch the value for t_mall_order_info.sku_mch
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuMch(String skuMch) {
        this.skuMch = skuMch == null ? null : skuMch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order_info.shp_tp
     *
     * @return the value of t_mall_order_info.shp_tp
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getShpTp() {
        return shpTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order_info.shp_tp
     *
     * @param shpTp the value for t_mall_order_info.shp_tp
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setShpTp(String shpTp) {
        this.shpTp = shpTp == null ? null : shpTp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order_info.sku_jg
     *
     * @return the value of t_mall_order_info.sku_jg
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public BigDecimal getSkuJg() {
        return skuJg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order_info.sku_jg
     *
     * @param skuJg the value for t_mall_order_info.sku_jg
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuJg(BigDecimal skuJg) {
        this.skuJg = skuJg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order_info.sku_shl
     *
     * @return the value of t_mall_order_info.sku_shl
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getSkuShl() {
        return skuShl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order_info.sku_shl
     *
     * @param skuShl the value for t_mall_order_info.sku_shl
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuShl(Integer skuShl) {
        this.skuShl = skuShl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order_info.sku_kcdz
     *
     * @return the value of t_mall_order_info.sku_kcdz
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public String getSkuKcdz() {
        return skuKcdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order_info.sku_kcdz
     *
     * @param skuKcdz the value for t_mall_order_info.sku_kcdz
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setSkuKcdz(String skuKcdz) {
        this.skuKcdz = skuKcdz == null ? null : skuKcdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mall_order_info.gwch_id
     *
     * @return the value of t_mall_order_info.gwch_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public Integer getGwchId() {
        return gwchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mall_order_info.gwch_id
     *
     * @param gwchId the value for t_mall_order_info.gwch_id
     *
     * @mbg.generated Tue Sep 12 20:59:26 CST 2017
     */
    public void setGwchId(Integer gwchId) {
        this.gwchId = gwchId;
    }
}